### ISSUE TITLE
When fidget spinner running environment view reads “Build Finished” but it shouldn't

### ISSUE THREAD

**Issue by chowbertilla** [DashboardHub/PipelineDashboard#973]
### Requirements

**API**
- [ ] Task One
- [ ] Task Two

**UI**
- [ ] Task One
- [ ] Task Two

**Comment by sarajaoude** [comment]
This is actually correct, because the environment type is `build-deploy`, the `Build Finished` state is not an end state, there is still `Start Deploy` and then `Finish Deploy` will be the end state.

<img width="426" alt="screenshot 2018-06-06 10 27 58" src="https://user-images.githubusercontent.com/11989248/41029731-60d66bea-6974-11e8-82d7-3a97dc18cff0.png">
